theme: jekyll-theme-primer
title: Dog Breed Classification
description: CS109A Final Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
